In [1]:
from __future__ import print_function
import torch

In [2]:
import torch
torch.cuda.is_available()

True

### Tensor

In [3]:
# Unintialised
x = torch.empty(5, 3)
x

tensor([[9.2755e-39, 1.0561e-38, 9.7347e-39],
        [1.0561e-38, 4.7756e-39, 4.2246e-39],
        [1.0286e-38, 1.0653e-38, 1.0194e-38],
        [8.4490e-39, 1.0469e-38, 9.3674e-39],
        [9.9184e-39, 8.7245e-39, 9.2755e-39]])

In [4]:
# Randomly initialised
x = torch.rand(5, 3)
x

tensor([[0.5338, 0.0167, 0.1677],
        [0.3873, 0.5381, 0.7056],
        [0.0400, 0.1326, 0.5194],
        [0.7264, 0.5371, 0.7945],
        [0.6066, 0.8223, 0.9859]])

In [5]:
# Zero matrix
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [6]:
# Construct from data
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

#### create a tensor based on an existing tensor: <br/>
These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                               

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.2673, -0.1036, -0.5689],
        [-0.6372,  1.0844,  1.9950],
        [-0.7643,  1.4240,  0.7920],
        [ 0.5363,  1.4081,  0.9431],
        [ 0.9294, -0.4158, -1.0742]])


In [8]:
# Get tensor size
print(x.size())

torch.Size([5, 3])


### Operations

In [9]:
# Addition
y = torch.rand(5, 3)
print(x + y)

print(torch.add(x, y))

tensor([[ 0.6679,  0.7127, -0.5006],
        [-0.3320,  1.1001,  2.6817],
        [-0.2101,  2.2257,  1.1279],
        [ 0.5422,  2.2372,  1.5473],
        [ 0.9784, -0.3292, -0.4102]])
tensor([[ 0.6679,  0.7127, -0.5006],
        [-0.3320,  1.1001,  2.6817],
        [-0.2101,  2.2257,  1.1279],
        [ 0.5422,  2.2372,  1.5473],
        [ 0.9784, -0.3292, -0.4102]])


In [10]:
# Addition to an output
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.6679,  0.7127, -0.5006],
        [-0.3320,  1.1001,  2.6817],
        [-0.2101,  2.2257,  1.1279],
        [ 0.5422,  2.2372,  1.5473],
        [ 0.9784, -0.3292, -0.4102]])


In [11]:
# Addition in-place
y.add_(x)
y

tensor([[ 0.6679,  0.7127, -0.5006],
        [-0.3320,  1.1001,  2.6817],
        [-0.2101,  2.2257,  1.1279],
        [ 0.5422,  2.2372,  1.5473],
        [ 0.9784, -0.3292, -0.4102]])

#### * Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.

In [12]:
# Numpy indexing
print(x[:, 1])

tensor([-0.1036,  1.0844,  1.4240,  1.4081, -0.4158])


In [13]:
# Resizing
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)   # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [14]:
# Get the value in one element tensors as a scalar 
x = torch.randn(1)
print(x.item())

1.6542985439300537


### Numpy Bridge

The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.

In [15]:
# Converting a Torch Tensor to a NumPy Array
a = torch.ones(5)
print(a)
b = a.numpy()
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [16]:
# Converting NumPy Array to Torch Tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### CUDA Tensors

Tensors can be moved onto any device using the .to method.

In [18]:
gpu = torch.device("cuda")  # a CUDA device object
y = torch.ones_like(x, device=gpu)  # directly create a tensor on GPU
x = x.to(gpu)    # or just use strings ``.to("cuda")``

z = x + y
print(z)
print(z.to("cpu", torch.double))

tensor([2.6543], device='cuda:0')
tensor([2.6543], dtype=torch.float64)
